### PR TITLE
[13.0][MIG] website_hr_recruitment

### PR DESCRIPTION
**Pull request by agustinbloopark**
Migration of website_hr_recruitment

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by AMhadhbi** [comment]
@agustinbloopark please update the doc file (odoo/openupgrade/doc/source/modules120-130.rs)t and put in website_hr_recruitment Nothing to do

**Comment by agustinbloopark** [comment]
> @agustinbloopark please update the doc file (odoo/openupgrade/doc/source/modules120-130.rs)t and put in website_hr_recruitment Nothing to do

done @AMhadhbi

**Comment by AMhadhbi** [comment]
@agustinbloopark please do it in one commit :) and pull the changes from master-staging-13. thanks

**Comment by bishalgit** [comment]
@agustinbloopark You can use rebase for this.
You want to git rebase -i to perform an interactive rebase.

If you're currently on your "commit 1", and the commit you want to merge, "commit 2", is the previous commit, you can run git rebase -i HEAD~2, which will spawn an editor listing all the commits the rebase will traverse. You should see two lines starting with "pick". To proceed with squashing, change the first word of the second line from "pick" to "squash". Then save your file, and quit. Git will squash your first commit into your second last commit.

Note that this process rewrites the history of your branch. If you are pushing your code somewhere, you'll have to git push -f and anybody sharing your code will have to jump through some hoops to pull your changes.

Note that if the two commits in question aren't the last two commits on the branch, the process will be slightly different.

**Review by bishalgit — APPROVED** [review]

**Comment by jholze** [comment]
I can't approve this PR, because it's Friday. Guys, I wish you a nice weekend :)

**Pull request merged**
